global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'

  - job_name: 'upload-service'
    static_configs:
      - targets: ['upload-service:8001']
    metrics_path: '/metrics'

  - job_name: 'viewer-page-service'
    static_configs:
      - targets: ['viewer-page-service:8002']
    metrics_path: '/metrics'

  - job_name: 'security-service'
    static_configs:
      - targets: ['security-service:8004']
    metrics_path: '/metrics'

  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:8005']
    metrics_path: '/metrics'

  - job_name: 'processing-service'
    static_configs:
      - targets: ['processing-service:8006']
    metrics_path: '/metrics'

  - job_name: 'transform-service'
    static_configs:
      - targets: ['transform-service:8007']
    metrics_path: '/metrics'